"""
bridges/gmat.py

Export bridge for General Mission Analysis Tool (GMAT).
Generates syntactically valid GMAT (.script) files seeded with preliminary
trajectory initial states, encounter epochs, and impulsive maneuvers (DSMs/flybys).
"""
from typing import Optional, Union
from astropy.time import Time

from orbital_mechanics.transfers.single_leg import SingleLegTransfer
from orbital_mechanics.maneuvers.dsm import DSMTransfer
from orbital_mechanics.transfers.multi_leg import MGATrajectory


def _jd_to_gmat_utc(jd: float) -> str:
    """Convert a Julian Date float to GMAT UTCGregorian string format (DD Mon YYYY HH:MM:SS.SSS)."""
    t = Time(jd, format="jd", scale="tdb")
    dt = t.to_datetime()
    return dt.strftime("%d %b %Y %H:%M:%S.%f")[:-3]


def export_to_gmat_script(
    trajectory: Union[SingleLegTransfer, DSMTransfer, MGATrajectory],
    output_path: Optional[str] = None,
    spacecraft_name: str = "Spacecraft",
    dry_mass_kg: float = 500.0,
) -> str:
    """
    Export an interplanetary trajectory to a GMAT .script file.

    Parameters
    ----------
    trajectory : SingleLegTransfer | DSMTransfer | MGATrajectory
        The solved trajectory object to export.
    output_path : str, optional
        File path to save the generated GMAT script. If None, only returns string.
    spacecraft_name : str, optional
        Name of the GMAT spacecraft object (defaults to "Spacecraft").
    dry_mass_kg : float, optional
        Spacecraft dry mass in kilograms (defaults to 500.0).

    Returns
    -------
    str
        The complete GMAT script text.
    """
    lines = []
    lines.append("%------------------------------------------------------------------------------")
    lines.append("% GMAT Mission Script generated by orbital-mechanics astrodynamics library")
    lines.append("% Purpose: Seed high-fidelity N-body numerical propagation & refinement")
    lines.append("%------------------------------------------------------------------------------")
    lines.append("")

    # Determine initial state and epoch
    if isinstance(trajectory, SingleLegTransfer):
        initial_epoch_jd = trajectory.departure_epoch
        init_pos = trajectory.departure_state_craft.position
        init_vel = trajectory.departure_state_craft.velocity
    elif isinstance(trajectory, DSMTransfer):
        initial_epoch_jd = trajectory.departure_epoch
        init_pos = trajectory.departure_state_craft.position
        init_vel = trajectory.departure_state_craft.velocity
    elif isinstance(trajectory, MGATrajectory):
        initial_epoch_jd = trajectory.epochs[0]
        init_pos = trajectory.legs[0].departure_state_craft.position
        init_vel = trajectory.legs[0].departure_state_craft.velocity
    else:
        raise TypeError(f"Unsupported trajectory type: {type(trajectory)}")

    epoch_str = _jd_to_gmat_utc(initial_epoch_jd)

    # Coordinate Systems
    lines.append("%------------------------------------------------------------------------------")
    lines.append("% Coordinate Systems")
    lines.append("%------------------------------------------------------------------------------")
    lines.append("Create CoordinateSystem SunICRF;")
    lines.append("GMAT SunICRF.Origin = Sun;")
    lines.append("GMAT SunICRF.Axes = ICRF;")
    lines.append("")

    # Spacecraft Configuration
    lines.append("%------------------------------------------------------------------------------")
    lines.append("% Spacecraft Definition")
    lines.append("%------------------------------------------------------------------------------")
    lines.append(f"Create Spacecraft {spacecraft_name};")
    lines.append(f"GMAT {spacecraft_name}.DateFormat = UTCGregorian;")
    lines.append(f"GMAT {spacecraft_name}.Epoch = '{epoch_str}';")
    lines.append(f"GMAT {spacecraft_name}.CoordinateSystem = SunICRF;")
    lines.append(f"GMAT {spacecraft_name}.DisplayStateType = Cartesian;")
    lines.append(f"GMAT {spacecraft_name}.X = {init_pos[0]:.6f};")
    lines.append(f"GMAT {spacecraft_name}.Y = {init_pos[1]:.6f};")
    lines.append(f"GMAT {spacecraft_name}.Z = {init_pos[2]:.6f};")
    lines.append(f"GMAT {spacecraft_name}.VX = {init_vel[0]:.8f};")
    lines.append(f"GMAT {spacecraft_name}.VY = {init_vel[1]:.8f};")
    lines.append(f"GMAT {spacecraft_name}.VZ = {init_vel[2]:.8f};")
    lines.append(f"GMAT {spacecraft_name}.DryMass = {dry_mass_kg:.1f};")
    lines.append("")

    # Propagator
    lines.append("%------------------------------------------------------------------------------")
    lines.append("% Propagator Setup")
    lines.append("%------------------------------------------------------------------------------")
    lines.append("Create ForceModel HeliocentricForceModel;")
    lines.append("GMAT HeliocentricForceModel.CentralBody = Sun;")
    lines.append("GMAT HeliocentricForceModel.PointMasses = {Sun, Earth, Venus, Mars, Mercury, Jupiter};")
    lines.append("GMAT HeliocentricForceModel.Drag = None;")
    lines.append("GMAT HeliocentricForceModel.SRP = Off;")
    lines.append("")
    lines.append("Create Propagator HeliousProp;")
    lines.append("GMAT HeliousProp.FM = HeliocentricForceModel;")
    lines.append("GMAT HeliousProp.Type = PrinceDormand78;")
    lines.append("GMAT HeliousProp.InitialStepSize = 3600;")
    lines.append("GMAT HeliousProp.Accuracy = 1e-11;")
    lines.append("GMAT HeliousProp.MinStep = 10;")
    lines.append("GMAT HeliousProp.MaxStep = 86400;")
    lines.append("")

    # Maneuvers & Mission Sequence Generation
    burn_definitions = []
    mission_commands = []
    mission_commands.append("BeginMissionSequence;")

    if isinstance(trajectory, SingleLegTransfer):
        mission_commands.append(f"Propagate HeliousProp({spacecraft_name}) {{{spacecraft_name}.ElapsedDays = {trajectory.tof_days:.4f}}};")

    elif isinstance(trajectory, DSMTransfer):
        dv_dsm = trajectory.delta_v_dsm
        burn_definitions.append("Create ImpulsiveBurn DSM_Burn;")
        burn_definitions.append("GMAT DSM_Burn.CoordinateSystem = SunICRF;")
        burn_definitions.append(f"GMAT DSM_Burn.Element1 = {dv_dsm[0]:.8f};")
        burn_definitions.append(f"GMAT DSM_Burn.Element2 = {dv_dsm[1]:.8f};")
        burn_definitions.append(f"GMAT DSM_Burn.Element3 = {dv_dsm[2]:.8f};")

        mission_commands.append(f"Propagate HeliousProp({spacecraft_name}) {{{spacecraft_name}.ElapsedDays = {trajectory.tof_leg1_days:.4f}}};")
        mission_commands.append(f"Maneuver DSM_Burn({spacecraft_name});")
        mission_commands.append(f"Propagate HeliousProp({spacecraft_name}) {{{spacecraft_name}.ElapsedDays = {trajectory.tof_leg2_days:.4f}}};")

    elif isinstance(trajectory, MGATrajectory):
        for i, leg in enumerate(trajectory.legs):
            if isinstance(leg, SingleLegTransfer):
                mission_commands.append(f"Propagate HeliousProp({spacecraft_name}) {{{spacecraft_name}.ElapsedDays = {leg.tof_days:.4f}}};")
            elif isinstance(leg, DSMTransfer):
                burn_name = f"DSM_Leg_{i}"
                dv_dsm = leg.delta_v_dsm
                burn_definitions.append(f"Create ImpulsiveBurn {burn_name};")
                burn_definitions.append(f"GMAT {burn_name}.CoordinateSystem = SunICRF;")
                burn_definitions.append(f"GMAT {burn_name}.Element1 = {dv_dsm[0]:.8f};")
                burn_definitions.append(f"GMAT {burn_name}.Element2 = {dv_dsm[1]:.8f};")
                burn_definitions.append(f"GMAT {burn_name}.Element3 = {dv_dsm[2]:.8f};")

                mission_commands.append(f"Propagate HeliousProp({spacecraft_name}) {{{spacecraft_name}.ElapsedDays = {leg.tof_leg1_days:.4f}}};")
                mission_commands.append(f"Maneuver {burn_name}({spacecraft_name});")
                mission_commands.append(f"Propagate HeliousProp({spacecraft_name}) {{{spacecraft_name}.ElapsedDays = {leg.tof_leg2_days:.4f}}};")

            # If there is a powered flyby deflection / correction at encounter
            if i < len(trajectory.flybys):
                fb = trajectory.flybys[i]
                if fb.delta_v_peri > 1e-4:
                    burn_name = f"Powered_Flyby_Burn_{i+1}"
                    dv_fb = fb.v_inf_out - fb.v_inf_in
                    burn_definitions.append(f"Create ImpulsiveBurn {burn_name};")
                    burn_definitions.append(f"GMAT {burn_name}.CoordinateSystem = SunICRF;")
                    burn_definitions.append(f"GMAT {burn_name}.Element1 = {dv_fb[0]:.8f};")
                    burn_definitions.append(f"GMAT {burn_name}.Element2 = {dv_fb[1]:.8f};")
                    burn_definitions.append(f"GMAT {burn_name}.Element3 = {dv_fb[2]:.8f};")
                    mission_commands.append(f"Maneuver {burn_name}({spacecraft_name});")

    if burn_definitions:
        lines.append("%------------------------------------------------------------------------------")
        lines.append("% Impulsive Burns")
        lines.append("%------------------------------------------------------------------------------")
        lines.extend(burn_definitions)
        lines.append("")

    lines.append("%------------------------------------------------------------------------------")
    lines.append("% Mission Sequence")
    lines.append("%------------------------------------------------------------------------------")
    lines.extend(mission_commands)
    lines.append("")

    script_text = "\n".join(lines)

    if output_path is not None:
        with open(output_path, "w") as f:
            f.write(script_text)

    return script_text
